# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
url: "https://fearlesssalarynegotiation.com"
baseurl: 
title: Fearless Salary Negotiation—A step-by-step guide to getting paid what you’re worth
email: josh@joshdoody.com
description: Get paid what you’re worth
avg_coach_increase: $13,310
avg_coach_increase_devs: $46,150
avg_coach_increase_non_devs: $29,191
# Build settings
markdown: kramdown
exclude:
  - vendor

permalink: /:title/

plugins:
  - jekyll-sitemap

collections:
  book_chapters:
    output: true
    permalink: /book/:title/
  book_excerpts:
    output: true
    permalink: /book/:path/
  podcasts:
    output: true
    permalink: /:title/
  redirects:
    output: true
    permalink: /:title/
  ads:
    output: true
    permalink: /:collection/:path