# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fearless Salary Negotiation—A step-by-step guide to getting paid what you're worth
email: josh@joshdoody.com
description: Everything you need to get paid what you're worth throughout your career.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fearlesssalarynegotiation.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
