# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
url: "https://fearlesssalarynegotiation.com"
baseurl: 
title: Fearless Salary Negotiation—A step-by-step guide to getting paid what you're worth
email: josh@joshdoody.com
description: I will show you how to get paid what you're worth
# Build settings
markdown: kramdown
exclude:
  - vendor

permalink: /:title/

gems:
  - jekyll-sitemap

collections:
  book_chapters:
    output: true
    permalink: /book/:title/
  book_excerpts:
    output: true
    permalink: /:title/
  podcasts:
    output: true
    permalink: /:title/